---
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:10.11.11
    container_name: jellyfin
    networks:
      - medianet
    volumes:
      - jellyfin_data:/config
      - /chungus/media/tvshows:/data/tvshows
      - /chungus/media/movies:/data/movies
    ports:
      # - "8920:8920"
      - "8096:8096"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    labels:
      - docktail.service.enable=true
      - docktail.service.name=jellyfin
      - docktail.service.description=Jellyfin media server
      - docktail.service.port=8096
      - docktail.service.protocol=http
      - docktail.service.direct=true
      - docktail.service.network=medianet
      - docktail.service.service-port=443
      - docktail.service.service-protocol=https
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr:6.3.0
    container_name: radarr
    networks:
      - medianet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - radarr_data:/config
      - /chungus/media/movies:/movies
      - /chungus/media/downloads:/downloads
    ports:
      - "7878:7878"
    labels:
      - docktail.service.enable=true
      - docktail.service.name=radarr
      - docktail.service.description=Radarr movie manager
      - docktail.service.port=7878
      - docktail.service.protocol=http
      - docktail.service.direct=true
      - docktail.service.network=medianet
      - docktail.service.service-port=443
      - docktail.service.service-protocol=https
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.19
    container_name: sonarr
    networks:
      - medianet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - sonarr_data:/config
      - /chungus/media/tvshows:/tvshows
      - /chungus/media/downloads:/downloads
    ports:
      - "8989:8989"
    labels:
      - docktail.service.enable=true
      - docktail.service.name=sonarr
      - docktail.service.description=Sonarr TV manager
      - docktail.service.port=8989
      - docktail.service.protocol=http
      - docktail.service.direct=true
      - docktail.service.network=medianet
      - docktail.service.service-port=443
      - docktail.service.service-protocol=https
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:2.5.2
    container_name: prowlarr
    networks:
      - medianet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - prowlarr_data:/config
    ports:
      - "9696:9696"
    labels:
      - docktail.service.enable=true
      - docktail.service.name=prowlarr
      - docktail.service.description=Prowlarr indexer manager
      - docktail.service.port=9696
      - docktail.service.protocol=http
      - docktail.service.direct=true
      - docktail.service.network=medianet
      - docktail.service.service-port=443
      - docktail.service.service-protocol=https
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:v3.4.1
    init: true
    container_name: seerr
    networks:
      - medianet
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Stockholm
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - seerr_config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    labels:
      - docktail.service.enable=true
      - docktail.service.name=seerr
      - docktail.service.description=Seerr media request portal
      - docktail.service.port=5055
      - docktail.service.protocol=http
      - docktail.service.direct=true
      - docktail.service.network=medianet
      - docktail.service.service-port=443
      - docktail.service.service-protocol=https
    restart: unless-stopped

networks:
  medianet:
    name: medianet

volumes:
  jellyfin_data:
    name: jellyfin_data
    external: true

  radarr_data:
    name: radarr_data
    external: true

  sonarr_data:
    name: sonarr_data
    external: true

  prowlarr_data:
    name: prowlarr_data
    external: true

  seerr_config:
    name: seerr_config
    external: true
