services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:2.17.1-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: always
volumes:
  portainer:
    name: portainer
