---
- name: Restart pveproxy
  ansible.builtin.service:
    name: pveproxy
    state: restarted

- name: Update initramfs
  become: true
  ansible.builtin.command: update-initramfs -u -k all
  changed_when: true

- name: Restart fr24feed
  ansible.builtin.systemd:
    name: fr24feed
    state: restarted

- name: UCI commit changes
  ansible.builtin.command: uci commit
  changed_when: true
