---
services:
  prowlarr:
    image: linuxserver/prowlarr:version-1.5.2.3484
    container_name: prowlarr
    networks:
      - medianet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - prowlarr_data:/config
    ports:
      - "9696:9696"
    restart: always

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.7
    container_name: flaresolverr
    networks:
      - medianet
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none  # Check repo for more options
      - TZ=Europe/Stockholm
    ports:
      - "8191:8191"
    restart: always

networks:
  medianet:
    external: true

volumes:
  prowlarr_data:
    external: true
