---
services:
  nginx:
    container_name: nginx_demo
    image: nginx:1.25.2-alpine
    volumes:
      - /docker/data/nginx_demo/nginx:/usr/share/nginx/html:ro
    ports:
      - "8088:80"
    restart: always
