---
services:
  app:
    image: ghcr.io/linuxserver/jellyfin:10.9.0
    networks:
      - medianet
    volumes:
      - jellyfin_data:/config
      - /certs/jellyfin:/certs
      - /chungus/media/tvshows:/data/tvshows
      - /chungus/media/movies:/data/movies
    ports:
      - "8920:8920"
      - "8096:8096"
    restart: unless-stopped

networks:
  medianet:
    external: true

volumes:
  jellyfin_data:
    name: jellyfin_data
