---
services:
  jellyfin:
    image: linuxserver/jellyfin:10.8.13
    networks:
      - medianet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - jellyfin_data:/config
      - /certs/jellyfin:/certs
      - /chungus/media/tvshows:/data/tvshows
      - /chungus/media/movies:/data/movies
    ports:
      - "8920:8920"
      - "8096:8096"
    restart: unless-stopped

networks:
  medianet:
    external: true

volumes:
  jellyfin_data:
    name: jellyfin_data
    external: true
