---
services:
  nginx:
    image: nginx:1.26.1-alpine
    container_name: nginx
    ports:
      - "8765:80"
    volumes:
      - /opt/election-map:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
