---
services:
  plausible_db:
    image: postgres:16-alpine
    networks:
      - plausible_network
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    restart: always
  plausible_events_db:
    image: clickhouse/clickhouse-server:24.7-alpine
    networks:
      - plausible_network
    volumes:
      - event_db:/var/lib/clickhouse
      - event_db_logs:/var/log/clickhouse-server
      - event_db_config:/etc/clickhouse-server
    deploy:
      mode: replicated
      replicas: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: always
  app:
    image: ghcr.io/plausible/community-edition:v2.1.1
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    networks:
      - plausible_network
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - "8888:8000"
    environment:
      - DISABLE_REGISTRATION=false
      - BASE_URL=${BASE_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - TOTP_VAULT_KEY=${TOTP_VAULT_KEY}
      - MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - MAXMIND_EDITION=GeoLite2-City
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - MAILER_ADAPTER=Bamboo.MailgunAdapter
      - MAILGUN_BASE_URI=https://api.eu.mailgun.net/v3
    restart: always

networks:
  plausible_network:
    external: true

volumes:
  db:
    name: plausible_db
    external: true
  event_db:
    name: plausible_event_db
    external: true
  event_db_logs:
    name: plausible_event_db_logs
    external: true
  event_db_config:
    name: plausible_event_db_config
    external: true
