services:
  app:
    image: ghcr.io/open-webui/open-webui:v0.3.12
    volumes:
      - data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=8083
    network_mode: host
    restart: unless-stopped

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    ports:
      - 9099:9099
    volumes:
      - pipelines:/app/pipelines
    restart: unless-stopped

volumes:
  data:
    driver: local
  pipelines:
    driver: local
