services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - 3100:8080
    volumes:
      - data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    network_mode: host
    restart: unless-stopped

volumes:
  data:
    driver: local
