---
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Stockholm
    ports:
      - 5055:5055
    networks:
      - medianet
    volumes:
      - ./jellyseerr_config:/app/config
    restart: unless-stopped

volumes:
  jellyseerr_config:
    external: true

networks:
  medianet:
    external: true
