---
- name: Create secret transmission_user
  community.docker.docker_secret:
    name: transmission_user
    data: "{{ lookup('community.general.onepassword', 'docker-transmission', field='transmission_user', vault='prod', service_account_token=env['OP_SERVICE_ACCOUNT_TOKEN']) }}"
    state: present

- name: Create secret transmission_pass
  community.docker.docker_secret:
    name: transmission_pass
    data: "{{ lookup('community.general.onepassword', 'docker-transmission', field='transmission_pass', vault='prod') }}"
    state: present

- name: Create network medianet
  community.docker.docker_network:
    name: medianet
    driver: overlay
    attachable: true
    state: present

- name: Deploy Watchtower
  community.docker.docker_compose:
    project_src: /docker/watchtower
    pull: true
    state: present

- name: Create network plausible_network
  community.docker.docker_network:
    name: plausible_network
    driver: overlay
    attachable: true
    state: present

- name: Deploy tsrecorder
  community.docker.docker_compose:
    project_src: /docker/tsrecorder
    pull: true
    state: present
  environment:
    TSRECORDER_AUTHKEY: "{{ lookup('community.general.onepassword', 'ts-authkey-recorder', field='credential', vault='prod') }}"

- name: Deploy prometheus-grafana
  community.docker.docker_compose:
    project_src: /docker/prometheus-grafana
    pull: true
    state: present

- name: Deploy Portainer
  community.docker.docker_stack:
    name: portainer
    compose:
      - /docker/portainer/compose.yaml
    state: present

- name: Deploy Radarr
  community.docker.docker_stack:
    name: radarr
    compose:
      - /docker/radarr/compose.yaml
    state: present

- name: Deploy Sonarr
  community.docker.docker_stack:
    name: sonarr
    compose:
      - /docker/sonarr/compose.yaml
    state: present

- name: Deploy Prowlarr
  community.docker.docker_stack:
    name: prowlarr
    compose:
      - /docker/prowlarr/compose.yaml
    state: present

- name: Deploy Jellyfin
  community.docker.docker_stack:
    name: jellyfin
    compose:
      - /docker/jellyfin/compose.yaml
    state: present

- name: Deploy transmission-wireguard
  community.docker.docker_compose:
    project_src: /docker/transmission-wireguard
    pull: true
    state: present

- name: Create secret cf_dns_api_token
  community.docker.docker_secret:
    name: cf_dns_api_token
    data: "{{ lookup('community.general.onepassword', 'cloudflare-dns-api-token', field='credential', vault='prod') }}"
    state: present

- name: Create network traefik
  community.docker.docker_network:
    name: traefik
    driver: overlay
    attachable: true
    state: present

- name: Deploy Traefik
  community.docker.docker_stack:
    name: traefik
    compose:
      - /docker/traefik/compose.yaml
    state: absent

- name: Create secret plausible_postgres_password
  community.docker.docker_secret:
    name: plausible_postgres_password
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_postgres_password', vault='prod') }}"
    state: present

- name: Create secret plausible_base_url
  community.docker.docker_secret:
    name: plausible_base_url
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_base_url', vault='prod') }}"
    state: present

- name: Create secret plausible_secret_key_base
  community.docker.docker_secret:
    name: plausible_secret_key_base
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_secret_key_base', vault='prod') }}"
    state: present

- name: Create secret plausible_maxmind_license_key
  community.docker.docker_secret:
    name: plausible_maxmind_license_key
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_maxmind_license_key', vault='prod') }}"
    state: present

- name: Create secret plausible_google_client_id
  community.docker.docker_secret:
    name: plausible_google_client_id
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_google_client_id', vault='prod') }}"
    state: present

- name: Create secret plausible_google_client_secret
  community.docker.docker_secret:
    name: plausible_google_client_secret
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_google_client_secret', vault='prod') }}"
    state: present

- name: Create secret plausible_mailgun_api_key
  community.docker.docker_secret:
    name: plausible_mailgun_api_key
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_mailgun_api_key', vault='prod') }}"
    state: present

- name: Create secret plausible_mailgun_domain
  community.docker.docker_secret:
    name: plausible_mailgun_domain
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_mailgun_domain', vault='prod') }}"
    state: present

- name: Deploy Plausible
  community.docker.docker_stack:
    name: plausible
    compose:
      - /docker/plausible/compose.yaml
    state: present

- name: Deploy Ombi
  community.docker.docker_stack:
    name: ombi
    compose:
      - /docker/ombi/compose.yaml
    state: present
