---
- name: Create network medianet
  community.docker.docker_network:
    name: medianet
    driver: overlay
    attachable: true
    state: present

- name: Create network plausible_network
  community.docker.docker_network:
    name: plausible_network
    driver: overlay
    attachable: true
    state: present

- name: Deploy Watchtower
  community.docker.docker_compose:
    project_src: /docker/watchtower
    pull: true
    state: present

- name: Deploy tsrecorder
  community.docker.docker_compose:
    project_src: /docker/tsrecorder
    pull: true
    state: present
  environment:
    TSRECORDER_AUTHKEY: "{{ lookup('community.general.onepassword', 'ts-authkey-recorder', field='credential', vault='prod', service_account_token=service_account_token) }}"

- name: Add authentik secrets
  ansible.builtin.template:
    src: ../../docker/authentik/.env.j2
    dest: /docker/authentik/.env
  vars:
    PG_DB: "{{ lookup('community.general.onepassword', 'docker-authentik', field='PG_DB', vault='prod', service_account_token=service_account_token) }}"
    PG_USER: "{{ lookup('community.general.onepassword', 'docker-authentik', field='PG_USER', vault='prod', service_account_token=service_account_token) }}"
    PG_PASS: "{{ lookup('community.general.onepassword', 'docker-authentik', field='PG_PASS', vault='prod', service_account_token=service_account_token) }}"
    AUTHENTIK_SECRET_KEY: "{{ lookup('community.general.onepassword', 'docker-authentik', field='AUTHENTIK_SECRET_KEY', vault='prod', service_account_token=service_account_token) }}"
    AUTHENTIK_EMAIL__HOST: "{{ lookup('community.general.onepassword', 'mailgun-smtp', field='smtp_host', vault='prod', service_account_token=service_account_token) }}"
    AUTHENTIK_EMAIL__PORT: "{{ lookup('community.general.onepassword', 'mailgun-smtp', field='smtp_port', vault='prod', service_account_token=service_account_token) }}"
    AUTHENTIK_EMAIL__USERNAME: "{{ lookup('community.general.onepassword', 'mailgun-smtp', field='smtp_username', vault='prod', service_account_token=service_account_token) }}"
    AUTHENTIK_EMAIL__PASSWORD: "{{ lookup('community.general.onepassword', 'mailgun-smtp', field='smtp_password', vault='prod', service_account_token=service_account_token) }}"
    AUTHENTIK_EMAIL__FROM: "{{ lookup('community.general.onepassword', 'mailgun-smtp', field='smtp_username', vault='prod', service_account_token=service_account_token) }}"

- name: Deploy authentik
  community.docker.docker_compose:
    project_src: /docker/authentik
    pull: true
    state: present

- name: Deploy Portainer
  community.docker.docker_stack:
    name: portainer
    compose:
      - /docker/portainer/compose.yaml
    state: present

- name: Deploy Radarr
  community.docker.docker_stack:
    name: radarr
    compose:
      - /docker/radarr/compose.yaml
    state: present

- name: Deploy Sonarr
  community.docker.docker_stack:
    name: sonarr
    compose:
      - /docker/sonarr/compose.yaml
    state: present

- name: Deploy Prowlarr
  community.docker.docker_stack:
    name: prowlarr
    compose:
      - /docker/prowlarr/compose.yaml
    state: present

- name: Deploy Jellyfin
  community.docker.docker_stack:
    name: jellyfin
    compose:
      - /docker/jellyfin/compose.yaml
    state: present

- name: Add wireguard secrets
  ansible.builtin.template:
    src: ../../docker/transmission-wireguard/wg0.conf.j2
    dest: /docker/transmission-wireguard/wg0.conf
  vars:
    private_key: "{{ lookup('community.general.onepassword', 'wg0', field='private_key', vault='prod', service_account_token=service_account_token) }}"
    public_key: "{{ lookup('community.general.onepassword', 'wg0', field='public_key', vault='prod', service_account_token=service_account_token) }}"
    endpoint: "{{ lookup('community.general.onepassword', 'wg0', field='endpoint', vault='prod', service_account_token=service_account_token) }}"

- name: Add transmission secrets
  ansible.builtin.template:
    src: ../../docker/transmission-wireguard/secrets.env.j2
    dest: /docker/transmission-wireguard/secrets.env
  vars:
    transmission_user: "{{ lookup('community.general.onepassword', 'docker-transmission', field='transmission_user', vault='prod', service_account_token=service_account_token) }}"
    transmission_pass: "{{ lookup('community.general.onepassword', 'docker-transmission', field='transmission_pass', vault='prod', service_account_token=service_account_token) }}"

- name: Deploy transmission-wireguard
  community.docker.docker_compose:
    project_src: /docker/transmission-wireguard
    pull: true
    state: present

- name: Deploy Ombi
  community.docker.docker_stack:
    name: ombi
    compose:
      - /docker/ombi/compose.yaml
    state: present

- name: Create secret plausible_postgres_password
  community.docker.docker_secret:
    name: plausible_postgres_password
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_postgres_password', vault='prod', service_account_token=service_account_token) }}"
    state: present

- name: Create secret plausible_base_url
  community.docker.docker_secret:
    name: plausible_base_url
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_base_url', vault='prod', service_account_token=service_account_token) }}"
    state: present

- name: Create secret plausible_secret_key_base
  community.docker.docker_secret:
    name: plausible_secret_key_base
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_secret_key_base', vault='prod', service_account_token=service_account_token) }}"
    state: present

- name: Create secret plausible_maxmind_license_key
  community.docker.docker_secret:
    name: plausible_maxmind_license_key
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_maxmind_license_key', vault='prod', service_account_token=service_account_token) }}"
    state: present

- name: Create secret plausible_google_client_id
  community.docker.docker_secret:
    name: plausible_google_client_id
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_google_client_id', vault='prod', service_account_token=service_account_token) }}"
    state: present

- name: Create secret plausible_google_client_secret
  community.docker.docker_secret:
    name: plausible_google_client_secret
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_google_client_secret', vault='prod', service_account_token=service_account_token) }}"
    state: present

- name: Create secret plausible_mailgun_api_key
  community.docker.docker_secret:
    name: plausible_mailgun_api_key
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_mailgun_api_key', vault='prod', service_account_token=service_account_token) }}"
    state: present

- name: Create secret plausible_mailgun_domain
  community.docker.docker_secret:
    name: plausible_mailgun_domain
    data: "{{ lookup('community.general.onepassword', 'docker-plausible', field='plausible_mailgun_domain', vault='prod', service_account_token=service_account_token) }}"
    state: present

- name: Deploy Plausible
  community.docker.docker_stack:
    name: plausible
    compose:
      - /docker/plausible/compose.yaml
    state: present
