---
- name: Download Fedora-Cloud-Base-37-1.7.x86_64.qcow2
  ansible.builtin.get_url:
    url: https://download.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.qcow2
    dest: /var/lib/vz/template/cloudimg/Fedora-Cloud-Base-37-1.7.x86_64.qcow2
    mode: '0640'

- name: Create Fedora Template
  community.general.proxmox_kvm:
    api_user: "{{ lookup('community.general.onepassword', 'hogsmeade', field='username', vault='prod', service_account_token=service_account_token) }}@pam"
    api_password: "{{ lookup('community.general.onepassword', 'hogsmeade', field='password', vault='prod', service_account_token=service_account_token) }}"
    api_host: hogsmeade
    node: hogsmeade

    vmid: 1000
    name: fedora-template
    machine: q35
    cpu: host
    cores: 4
    memory: 4096
    bios: ovmf
    ostype: l26
    agent: 1
    scsihw: virtio-scsi-pci
    net:
      net0: virtio,bridge=vmbr0
    efidisk0:
      storage: local-lvm
      format: raw
      efitype: 4m
      pre_enrolled_keys: 1
    ide:
      ide2: local-lvm:cloudinit,format=raw
    serial:
      serial0: socket
    vga: serial0
    bootdisk: scsi0
    ciuser: "{{ lookup('community.general.onepassword', 'mediaserver', field='username', vault='prod', service_account_token=service_account_token) }}"
    cipassword: "{{ lookup('community.general.onepassword', 'mediaserver', field='password', vault='prod', service_account_token=service_account_token) }}"
    sshkeys: "{{ lookup('community.general.onepassword', 'Sebastian SSH Public Key', field='public key', vault='prod', service_account_token=service_account_token) }}"
    timeout: 180
    state: present
  register: fedora_template

- name: Import Fedora Cloud Base image  # noqa no-handler
  ansible.builtin.shell: /usr/sbin/qm disk import 1000 /var/lib/vz/template/cloudimg/Fedora-Cloud-Base-37-1.7.x86_64.qcow2 local-lvm --format qcow2; /usr/sbin/qm set 1000 --scsi0 local-lvm:vm-1000-disk-1;/usr/sbin/qm set 1000 --boot order=scsi0; /usr/sbin/qm template 1000  # noqa yaml
  when: fedora_template.changed

- name: Clone fedora_template to mediaserver
  community.general.proxmox_kvm:
    api_user: "{{ lookup('community.general.onepassword', 'hogsmeade', field='username', vault='prod', service_account_token=service_account_token) }}@pam"
    api_password: "{{ lookup('community.general.onepassword', 'hogsmeade', field='password', vault='prod', service_account_token=service_account_token) }}"
    api_host: hogsmeade
    node: hogsmeade
    clone: fedora-template
    full: true
    vmid: 1000
    newid: 100
    name: mediaserver
    onboot: true
    timeout: 300
    state: present
  register: mediaserver
  notify:
    - resize_vm
