---
- name: Add flightradar24 repository
  ansible.builtin.deb822_repository:
    name: flightradar24
    types: deb
    signed_by: https://repo-feed.flightradar24.com/flightradar24.pub
    uris: https://repo-feed.flightradar24.com
    suites: flightradar24
    components: raspberrypi-stable
    state: present

- name: Add FlightAware repository
  ansible.builtin.deb822_repository:
    name: flightaware-apt-repository
    types: deb
    uris: http://flightaware.com/adsb/piaware/files/packages
    suites: bookworm
    components: piaware
    signed_by: |-
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQINBFQp58QBEADVe1aklQJZ9qwJGqDI68sxwe/25XkaazmklWgpafIkqRk5HtnY
      n37iSn0RQrd+ggKQJ+fYUb+hcUCKf6BegNhJAEW1HId6pagUXhCAm/T7DQbphv0b
      mzzIpna2FN02xqL9wNfc+druZUEvNvicktymxdrVXX3hsYSP7b80e7Vsc1R0pcsw
      xR9Sr2HRn9g4JUIUBC3WYMw14wCUCIRHWXcSEhOZEJsPcZ5XknNR6F7ydzPhTDC/
      5TxXEtGmybuatE9p36dk9VPPn/oqq8SCJdhjjPth0Cu4xsYm/no984D8hN4phqsw
      HFYd7Uf93VhOiHZqlExMgQWZsv7cS1wCKBvjerAWcBCE4Iwhxbdi1RHRO9w3U2z5
      P4hAxmdCncQdVTMPlaDfwAyyuGN1Qx3ji2uIahuH7W2pX5U5RH4csZpfnP9t6szh
      cxnNO5t7NFOOaxP8TJ00iZIP6aP3fELZ2yieZsJpJ8gwFldNOzbL/UwKgkJAClGj
      1sKFZ1yzzbbwmTO+tztzuYUuU1gri9Dy/J73sRWgUVgxPzf2Ng9HOYEeOwzYNUEp
      /ozPGHZtAaazI8xfsh6jcTiauWxaBvVZRW09PS9wwxcUDoc/3aLu8WoPuLpSjrYC
      yucS6F/+3JVbcwPyV19nLZUsKmmDRoNKIjSCcbK9wEKe2KpNeQY+aiqo4wARAQAB
      tDJGbGlnaHRBd2FyZSBEZXZlbG9wZXJzIDxhZHNiLWRldnNAZmxpZ2h0YXdhcmUu
      Y29tPokCOAQTAQIAIgUCVCnnxAIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AA
      CgkQuTG7KN6F8N2AmRAAlyS82cTY2wL9LfaDhXtGFJb/rYLjy9pa7r5p5w8VONcq
      2Xsq1KUjkk4CncaWEDmK4qu3jYAFfy2HUF2WDzAxc2vo1/jLRmLx8BP0Z1lfFBKo
      VhvPgHb77SqSTW8pdY3AJyiKdiaX8mA77T9rle2HSlZPZhdobiSv+acYHD2UUZmd
      w5LEKl2UDv6cM5vYKlYglQxGqVd/O4plFQUoW+rGKVkXYf3YajbS4Zde6c3n0isG
      6EmdmWSz02uHAbw8rW8pj7c7Kx9iTNVbpQOYXPabl9/Bd282/uE8LDLtwwxRZljK
      Ry+TKRboCC7mA1QJr8dhANlBPRDs/1twNTJakutaFlVAcjB01OX8n9lzGlXpkCcA
      UnbXAT0n+UsLLhxZWtBKNjn9BopB5aDc/bC2HARz/5lrMV9vfEcQs/a29ToOtzjI
      qefoBGzWKrTEAXDZrQbKGprVqWfKKrZirTse8E1fjcmI3ar3B4rusUswRRHRckLS
      qIacqz6WstZ8MoDSTzsiottTjmgXQWEinUaMnjaifT/Pc3fS+4k+sd++dYDjhSdK
      +fr8cIEPCUUu8Qg5sgkCgco2WaC7OGFaotdeIIZPoaZ/OGkS/Ih5RmdIBCchaWHW
      l88SUTUaEAeVRRGqPb/HzLOykPYeLWnB+TawdEF9chxstd4ZaMqJTDcyXOwEd9o=
      =dxeZ
      -----END PGP PUBLIC KEY BLOCK-----

- name: Install Flightradar24 and dependencies
  ansible.builtin.apt:
    name:
      - fr24feed
      - lighttpd
      - librtlsdr0
      - libusb-1.0-0
      - dump1090-fa # Use dump1090-fa instead of dump1090-mutability
      # - dump1090-mutability # Use dump1090-mutability instead of dump1090-fa
    update_cache: true
    dpkg_options: "force-confdef,force-confold"
    state: present

# Only needed if using dump1090-mutability
# - name: Create symbolic link for dump1090
#   ansible.builtin.file:
#     src: /usr/bin/dump1090-mutability
#     dest: /usr/lib/fr24/dump1090
#     state: link

# Only needed if using dump1090-mutability
# - name: Enable dump1090-mutability module for lighttpd
#   ansible.builtin.command: lighty-enable-mod dump1090
#   args:
#     creates: /etc/lighttpd/conf-enabled/89-dump1090.conf

- name: Enable dump1090-fa-statcache module for lighttpd
  ansible.builtin.command: lighty-enable-mod dump1090-fa-statcache
  args:
    creates: /etc/lighttpd/conf-enabled/88-dump1090-fa-statcache.conf

- name: Enable skyaware module for lighttpd (dump1090-fa)
  ansible.builtin.command: lighty-enable-mod skyaware
  args:
    creates: /etc/lighttpd/conf-enabled/89-skyaware.conf

- name: Enable and start lighttpd service
  ansible.builtin.systemd:
    name: lighttpd
    enabled: true
    state: started

- name: Configure fr24feed with sharing key
  ansible.builtin.template:
    src: fr24feed.ini.j2
    dest: /etc/fr24feed.ini
    mode: "0644"
    backup: true
  notify: Restart fr24feed
  when: fr24_sharing_key is defined

- name: Enable and start fr24feed service
  ansible.builtin.systemd:
    name: fr24feed
    enabled: true
    state: started

- name: Wait for fr24feed service to be ready
  ansible.builtin.wait_for:
    port: 8754
    host: localhost
    delay: 10
    timeout: 60
  register: wait_for_fr24feed
  failed_when: wait_for_fr24feed is failed and 'Timeout' not in wait_for_fr24feed.msg

- name: Verify fr24feed service status
  ansible.builtin.systemd:
    name: fr24feed
  register: fr24feed_status

- name: Display fr24feed service status
  ansible.builtin.debug:
    msg: "fr24feed service is {{ 'running' if fr24feed_status.status.ActiveState == 'active' else 'not running properly' }}"
