---
- name: Disable pve-enterprise repo
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: "^deb "
    replace: '# \g<0>'

- name: Add pve-no-subscription repo
  ansible.builtin.apt_repository:
    filename: pve-no-subscription
    repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
    mode: "0644"
    state: present

- name: Disable Proxmox subscription nag message
  ansible.builtin.replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: 'res[\s\n]*\.data\.status\.toLowerCase\(\) !== .active.'
    replace: false
    backup: true
  notify: restart pveproxy
