services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.10.5
    container_name: homepage
    ports:
      - 3010:3000
    volumes:
      - config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  config:
    driver: local
