- name: Hogsmeade Proxmox
  hosts: proxmox_nodes

  roles:
    - name: Install and configure Tailscale
      role: artis3n.tailscale
      tailscale_args: "--ssh"
      vars:
        tailscale_authkey: "{{ lookup('community.general.onepassword', 'ts-authkey-server', field='credential', vault='Private') }}"
      state: present

    - name: Remove PVE subscription nag, enable Dark Theme and manage repos
      role: simoncaron.pve_addons
      vars:
        pve_addons_enable_dark_theme: true
        pve_addons_remove_subscription_nag: true
        pve_addons_remove_enterprise_repo: true
        pve_addons_add_no_subscription_repo: true

  tasks:
    - name: Enable IOMMU in GRUB
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((:?(?!intel_iommu=on).)*?)"$'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 intel_iommu=on"'
        backup: true
        backrefs: true
      notify: update-grub

    - name: Enable nomodeset in GRUB
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((:?(?!nomodeset).)*?)"$'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 nomodeset"'
        backup: true
        backrefs: true
      notify: update-grub

    - name: Update hosts
      ansible.builtin.lineinfile:
        path: /etc/modules
        line: "{{ item }}"
        state: present
      with_items:
        - vfio
        - vfio_iommu_type1
        - vfio_pci
        - vfio_virqfd

    - name: SSH authorized key for 'root'
      ansible.posix.authorized_key:
        user: root
        key: "{{ lookup('community.general.onepassword', 'Sebastian SSH Key', field='public key', vault='Private') }}"
        state: present

    - name: Add sebastian public SSH key
      ansible.builtin.copy:
        src: ~/.ssh/sebastian_ed25519.pub
        dest: ~/.ssh/sebastian_ed25519.pub
        mode: 0644

    - name: Disable root login over SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin prohibit-password"
        state: present

    - name: Disable password login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present

    - name: Install nfs-kernel-server
      ansible.builtin.apt:
        name:
          - nfs-kernel-server
        state: present

    - name: Create ZFS filesystem and set sharenfs property
      community.general.zfs:
        name: chungus/media
        extra_zfs_properties:
          sharenfs: crossmnt,no_root_squash,rw=192.168.1.0/24
        state: present

    - name: Install proxmox_kvm dependencies
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-setuptools
          - python3-wheel
        state: present

    - name: Install proxmox_kvm
      ansible.builtin.pip:
        name:
          - proxmoxer
          - requests
        state: present

    - name: Download Fedora-Cloud-Base-37-1.7.x86_64.qcow2
      ansible.builtin.get_url:
        url: https://download.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.qcow2
        dest: /var/lib/vz/template/cloudimg/Fedora-Cloud-Base-37-1.7.x86_64.qcow2
        mode: 0640

    - name: Create Fedora Template
      community.general.proxmox_kvm:
        api_user: "{{ lookup('community.general.onepassword', 'hogsmeade', field='username', vault='Private') }}@pam"
        api_password: "{{ lookup('community.general.onepassword', 'hogsmeade', field='password', vault='Private') }}"
        api_host: hogsmeade
        node: hogsmeade

        vmid: 1000
        name: fedora-template
        machine: q35
        cpu: host
        cores: 2
        memory: 2048
        bios: ovmf
        ostype: l26
        agent: 1
        scsihw: virtio-scsi-pci
        net:
          net0: virtio,bridge=vmbr0
        efidisk0:
          storage: local-lvm
          format: raw
          efitype: 4m
          pre_enrolled_keys: 1
        ide:
          ide2: local-lvm:cloudinit,format=raw
        serial:
          serial0: socket
        vga: serial0
        bootdisk: scsi0
        ciuser: "{{ lookup('community.general.onepassword', 'mediaserver', field='username', vault='Private') }}"
        cipassword: "{{ lookup('community.general.onepassword', 'mediaserver', field='password', vault='Private') }}"
        sshkeys: "{{ lookup('community.general.onepassword', 'Sebastian SSH Key', field='public key', vault='Private') }}"
        timeout: 180
        state: present
      register: fedora_template

    - name: Import Fedora Cloud Base image # noqa no-handler
      ansible.builtin.shell: /usr/sbin/qm disk import 1000 /var/lib/vz/template/cloudimg/Fedora-Cloud-Base-37-1.7.x86_64.qcow2 local-lvm --format qcow2; /usr/sbin/qm set 1000 --scsi0 local-lvm:vm-1000-disk-1;/usr/sbin/qm set 1000 --boot order=scsi0; /usr/sbin/qm template 1000 # noqa yaml
      when: fedora_template.changed

    - name: Clone fedora_template to mediaserver
      community.general.proxmox_kvm:
        api_user: "{{ lookup('community.general.onepassword', 'hogsmeade', field='username', vault='Private') }}@pam"
        api_password: "{{ lookup('community.general.onepassword', 'hogsmeade', field='password', vault='Private') }}"
        api_host: hogsmeade
        node: hogsmeade
        clone: fedora-template
        full: true
        vmid: 1000
        newid: 100
        name: mediaserver
        timeout: 300
        state: present
      register: mediaserver
      notify:
        - resize_vm

  handlers:
    - name: Restart pveproxy
      ansible.builtin.service:
        name: pveproxy
        state: restarted

    - name: Update grub
      ansible.builtin.command:
        cmd: update-grub
      listen: update-grub

    - name: Resize VM
      ansible.builtin.command:
        cmd: /usr/sbin/qm resize {{ mediaserver.newid }} scsi0 +20G
      listen: resize_vm
