---
collections:
  - name: community.general
    version: 8.1.0

  - name: community.docker
    version: 3.4.11

  - name: ansible.posix
    version: 1.5.4

roles:
  - name: artis3n.tailscale
    src: https://github.com/artis3n/ansible-role-tailscale.git
    version: v4.2.3

  - name: simoncaron.pve_addons
    src: https://github.com/simoncaron/ansible-role-pve_addons.git
    version: 1.5.0

  - name: geerlingguy.docker
    src: https://github.com/geerlingguy/ansible-role-docker.git
    version: 7.0.2

  - name: sebdanielsson.cloudflared
    src: https://github.com/sebdanielsson/ansible-role-cloudflared.git
    version: 2.3.0
