---
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard:version-1.0.20210914-r4
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wgnet:
        ipv4_address: 172.100.0.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    ports:
      - 9091:9091
    volumes:
      - /lib/modules:/lib/modules
      - ./wg0.conf:/config/wg_confs/wg0.conf
    healthcheck:
      test: ["CMD-SHELL", "wg show | grep -q 'latest handshake:'"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
  transmission:
    image: ghcr.io/linuxserver/transmission:4.0.6
    container_name: transmission
    network_mode: "service:wireguard"
    depends_on:
      wireguard:
        condition: service_healthy
        restart: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - DOCKER_MODS=jordanpotter/docker-mods:transmission-nat-pmp
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - transmission_data:/config
      - /chungus/media/downloads:/downloads
    restart: unless-stopped

networks:
  wgnet:
    ipam:
      config:
        - subnet: 172.100.0.0/24
          ip_range: 172.100.0.0/24
          gateway: 172.100.0.1
    attachable: true

volumes:
  transmission_data:
    name: transmission_data
    external: true
