---
services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wgnet:
        ipv4_address: 172.100.0.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    ports:
      - 9091:9091
    volumes:
      - /lib/modules:/lib/modules
      - ./wg0.conf:/config/wg0.conf
    restart: always
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
  transmission:
    image: linuxserver/transmission:version-4.0.3-r2
    container_name: transmission
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    #env_file: # Comment out to test Docker secrets
    #  - secrets.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - FILE__USER=/run/secrets/transmission_user
      - FILE__PASS=/run/secrets/transmission_pass
      - DOCKER_MODS=jordanpotter/docker-mods:transmission-nat-pmp
    volumes:
      - transmission_data:/config
      - /chungus/media/downloads:/downloads
      - /run/secrets/transmission_user:/run/secrets/transmission_user
      - /run/secrets/transmission_pass:/run/secrets/transmission_pass
    restart: always

networks:
  wgnet:
    ipam:
      config:
        - subnet: 172.100.0.0/24
          ip_range: 172.100.0.0/24
          gateway: 172.100.0.1
    attachable: true

volumes:
  transmission_data:
    name: transmission_data
