---
services:
  traefik:
    image: traefik:v3.0.0-beta2
    command:
      - --api
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=WARN
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http3
      - --entrypoints.websecure.http3.advertisedport=443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.tailscale.tailscale=true
    networks:
      - traefik
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_dns_api_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock:ro
    ports:
      - "443:443"
      - "443:443/udp"
      - "8080:8080"
    secrets:
      - cf_dns_api_token
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`hogsmeade.risk-bee.ts.net`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.services.dashboard.loadbalancer.server.port=8080
      - traefik.http.routers.dashboard.tls.certresolver=tailscale
      - traefik.http.routers.dashboard.middlewares=secHeaders
      - traefik.http.middlewares.secHeaders.headers.browserXssFilter=true
      - traefik.http.middlewares.secHeaders.headers.contentTypeNosniff=true
      - traefik.http.middlewares.secHeaders.headers.frameDeny=true
      - traefik.http.middlewares.secHeaders.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.secHeaders.headers.stsPreload=true
      - traefik.http.middlewares.secHeaders.headers.stsSeconds=63072000
      - traefik.http.middlewares.secHeaders.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.secHeaders.headers.referrerPolicy=same-origin
      - traefik.http.middlewares.secHeaders.headers.PermissionsPolicy="geolocation=(self), microphone=(), camera=(), fullscreen=*"

secrets:
  cf_dns_api_token:
    external: true

networks:
  traefik:
    external: true

volumes:
  acme:
    name: traefik_acme
    external: true
