---
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.13.2
    networks:
      - prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    labels:
      - docktail.service.enable=true
      - docktail.service.name=prometheus
      - docktail.service.description=Prometheus metrics server
      - docktail.service.port=9090
      - docktail.service.protocol=http
      - docktail.service.direct=true
      - docktail.service.network=prometheus-grafana
      - docktail.service.service-port=443
      - docktail.service.service-protocol=https
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:13.1.3
    depends_on:
      - prometheus
    networks:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - docktail.service.enable=true
      - docktail.service.name=grafana
      - docktail.service.description=Grafana dashboards
      - docktail.service.port=3000
      - docktail.service.protocol=http
      - docktail.service.direct=true
      - docktail.service.network=prometheus-grafana
      - docktail.service.service-port=443
      - docktail.service.service-protocol=https
    restart: unless-stopped

networks:
  prometheus:
    name: prometheus-grafana

volumes:
  prometheus_data:
    name: prometheus_data
    external: true

  grafana_data:
    name: grafana_data
    external: true
