---
name: Lint

'on':
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: 'sebdanielsson.infra/ansible'

jobs:
  lint:
    name: Run yaml-lint and ansible-lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'sebdanielsson.infra'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Ansible dependencies
        run: |
          ansible-galaxy install -r requirements.yml

      - name: Lint code.
        run: |
          yamllint .

      - name: Run ansible-lint
        run: |
          ansible-lint .
