---
name: Lint

'on':
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: ansible-lint
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24
        with:
          setup_python: "true"
          requirements_file: "./requirements.yml"
