---
name: Lint

'on':
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: 'sebdanielsson.infra/ansible'

jobs:
  lint:
    name: Run yaml-lint and ansible-lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'sebdanielsson.infra'
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Install Ansible dependencies
        run: |
          ansible-galaxy install -r requirements.yml

      - name: Run yaml-lint
        uses: ibiqlik/action-yamllint@v3.1.1

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6.20.3
