---
name: Run playbook

'on':
  push:
    branches:
      - main
    paths:
      - ansible/**
  workflow_dispatch:

defaults:
  run:
    working-directory: 'sebdanielsson.infra/ansible'

jobs:
  run-playbook:
    name: Run playbook
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'sebdanielsson.infra'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Ansible dependencies
        run: |
          ansible-galaxy install -r requirements.yml

      - name: Disable host key checking
        run: |
          mkdir -p ~/.ssh
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
  
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load Tailscale token
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          TAILSCALE_AUTHKEY: op://prod/ts-authkey-ci/credential

      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          version: '1.50.1'
          authkey: ${{ env.TAILSCALE_AUTHKEY }}
          tags: tag:ci
          args: --ssh

      - name: Check op version
        run: |
          op --version

      - name: Run playbook
        run: |
          ansible-playbook -i inventory.yml ci-test.yml
