---
name: Run playbook

'on':
  push:
    branches:
      - main
    paths:
      - ansible/**
      - docker/**
  workflow_dispatch:

defaults:
  run:
    working-directory: 'sebdanielsson.infra/ansible'

jobs:
  run-playbook:
    name: Run playbook
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'sebdanielsson.infra'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Ansible dependencies
        run: |
          ansible-galaxy install -r requirements.yml

      - name: Disable host key checking
        run: |
          mkdir -p ~/.ssh
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
        with:
          version: latest

      - name: Load secret ts-authkey
        id: op-load-ts-authkey
        uses: 1password/load-secrets-action@v1
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          TS_AUTHKEY: op://prod/ts-authkey-ci/credential

      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          version: '1.50.1'
          authkey: ${{ steps.op-load-ts-authkey.outputs.TS_AUTHKEY }}
          tags: tag:ci
          args: --ssh

      - name: Run playbook
        run: |
          op run --env-file=.env -- ansible-playbook -i inventory.yml hogsmeade.yml
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

